# Generated by Django 5.1.7 on 2025-05-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registrant",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non-binary", "Non-binary"),
                        ],
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
                ("seed_time", models.CharField(max_length=255)),
                ("sponsor", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_place", models.IntegerField(null=True)),
                ("gender_place", models.IntegerField(null=True)),
                ("time", models.CharField(max_length=255)),
                ("dnf", models.BooleanField(default=False)),
                ("year", models.IntegerField()),
                (
                    "registrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_site.registrant",
                    ),
                ),
            ],
        ),
    ]
