# Generated by Django 5.1.7 on 2025-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrant",
            name="hometown",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
