# Generated by Django 5.1.7 on 2025-05-31 21:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrant",
            name="date_of_birth",
            field=models.DateField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1925, 5, 31),
                        message="Date of birth cannot be more than 100 years ago",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 5, 31),
                        message="Date of birth cannot be in the future",
                    ),
                ],
            ),
        ),
    ]
