# Generated by Django 6.0.5 on 2026-05-23 17:17

import django.core.validators
import main_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_remove_result_placement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=main_site.models.earliest_birth_date, message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=main_site.models.current_date, message='Date of birth cannot be in the future')]),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='year',
            field=models.IntegerField(default=main_site.models.current_year),
        ),
        migrations.AlterField(
            model_name='result',
            name='year',
            field=models.IntegerField(default=main_site.models.current_year),
        ),
    ]
